# Generated by Django 5.0.14 on 2026-09-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Shem Okebiro', max_length=120)),
                ('role', models.CharField(default='Designer & Developer', max_length=120)),
                ('tagline', models.CharField(default='Designing quiet, deliberate interfaces.', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Short bio shown under the headline.')),
                ('profile_picture', models.ImageField(blank=True, help_text='Used as the full-bleed homepage background.', null=True, upload_to='profile/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('location', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('short_description', models.CharField(blank=True, max_length=280)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('link', models.URLField(blank=True)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('instagram', 'Instagram'), ('dribbble', 'Dribbble'), ('behance', 'Behance'), ('email', 'Email'), ('website', 'Website'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Optional custom label.', max_length=80)),
                ('url', models.CharField(help_text='Full URL, or mailto: for email.', max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
